version: 2.1
executors:
  app-executor:
    docker:
      - image: circleci/node:12.9.0
    working_directory: ~/project
  slack-executor:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small