export const languagesList = () => [
  'Armenian',
  'Bulgarian',
  'Chinese (Mandarin)',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Estonian',
  'Finnish',
  'French',
  'Georgian',
  'German',
  'Greek',
  'Hindi',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Korean',
  'Latvian',
  'Lithuanian',
  'Macedonian',
  'Mongolian',
  'Norwegian',
  'Polish',
  'Portuguese',
  'Romanian',
  'Russian',
  'Serbian',
  'Slovak',
  'Slovenian',
  'Spanish',
  'Swedish ',
  'Turkish',
  'Ukrainian',
  'Uzbek',
  'Vietnamese'
];

export const photographyCategories = () => [
  'Wedding Photography',
  'Portrait Photography',
  'Still Life Photography',
  'Landscape Photography',
  'Food Photography',
  'Sports Photography',
  'Fine Art Photography',
  'Product Photography',
  'Wildlife Photography',
  'Travel Photography',
  'Macro Photography',
  'Event Photography',
  'Pet Photography',
  'Aerial Photography',
  'Fashion Photography',
  'Newborn Photography',
  'Street Photography',
  'Photojournalism Photography',
  'Documentary Photography',
  'Weather Photography',
  'Architectural Photography',
  'Long Exposure Photography',
  'Fashion Photography',
  'Family Photography'
];
